services:
  # Database PostgreSQL
  database:
    image: postgres:16-alpine
    container_name: foglio-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: foglio
      POSTGRES_USER: foglio
      POSTGRES_PASSWORD: foglio_password_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foglio-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foglio"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Spring Boot API
  backend:
    build:
      context: ./foglio-be
      dockerfile: Dockerfile
    container_name: foglio-backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/foglio
      SPRING_DATASOURCE_USERNAME: foglio
      SPRING_DATASOURCE_PASSWORD: foglio_password_2025
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      FILE_STORAGE_PATH: /app/files
    volumes:
      - files_data:/app/files
    networks:
      - foglio-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Nginx + Next.js
  frontend:
    build:
      context: ./foglio-fe
      dockerfile: Dockerfile
    container_name: foglio-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - foglio-network
    environment:
      - NEXT_PUBLIC_API_URL=/api

networks:
  foglio-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  files_data:
    driver: local
